# Environment that uses CUDA 11.6
name: fastforce
channels:
  - defaults
  - psi4
  - conda-forge
dependencies:
  - python==3.10.*
  - pandas==1.*
  - pydantic
  - psi4==1.6.1*
  - pymongo
  - tqdm
  - jupyterlab
  - matplotlib
  - tensorboard
  - pytest
  - pip
  - pip:
      # TODO (wardlt): Move these to a requirements file
      # Latest version of PyG: https://github.com/pyg-team/pytorch_geometric#pytorch-112
      - --extra-index-url https://download.pytorch.org/whl/cu116
      - -f https://data.pyg.org/whl/torch-1.12.0+cu116.html
      - torch-scatter==2.0.*
      - torch-sparse==0.6.*
      - torch-geometric==2.1.*
      - torch-cluster==1.6.*
      - torch==1.12.0+cu116
      - git+https://gitlab.com/WardLT/ase.git@twostep_nwc
      - colmena>=0.3.0
      - globus-cli
      - schnetpack==1.*
      - globus-compute-sdk
      - globus-compute-endpoint
      - -e .
